"use strict"

module.exports = {
  url: "https://developer-diary.netlify.com",
  title: "Contemplate",
  tagline: "Autodidact Developer and Innovator",
  copyright: "© 2019 SajNair, All rights reserved",
  author: {
    name: "Sajjal Nair",
    bio: "Web Developer and a movie enthusiast",
    contacts: {
      linkedin: "https://www.linkedin.com/in/sajjal-nair-29a301158/",
      github: "https://github.com/nairsajjal",
      },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ruby",
      tech: "Ruby",
      name: "DiRuby",
      size: 20,
      color: "crimson",
    },
    {
      tag: "java",
      tech: "Java",
      name: "FaJava",
      size: 20,
      color: "wheat",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "php",
      tech: "php",
      name: "DiPhp",
      size: 20,
      color: "violet",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
  ],
}
